# Generated by Django 2.2.3 on 2022-12-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='mensajeria',
        ),
    ]
