# Generated by Django 2.2.3 on 2022-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientes_mensajeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='dafault', max_length=15),
            preserve_default=False,
        ),
    ]
