# Generated by Django 2.2.3 on 2022-12-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='nombre',
        ),
    ]
